spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goalhub
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
api:
  football:
    url: https://api-football-v1.p.rapidapi.com/v3
    key: "f95062b646msh501f47ec3b95547p129498jsnfcd363840490"